behaviors:
  AgentBehavior:
    trainer_type: ppo
    init_path: "results/model_stage_3/AgentBehavior/checkpoint.pt"
    hyperparameters:
      batch_size: 64
      buffer_size: 1000
      learning_rate: 8.0e-4
      beta: 3.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    #   gail:
    #     strength: 0.5
    #     demo_path: Demos/Navigation1.demo
    # behavioral_cloning:
    #   strength: 0.5
    #   demo_path: Demos/Navigation1.demo
    max_steps: 700000
    time_horizon: 128
    summary_freq: 10000